### ISSUE TITLE
help

### ISSUE THREAD

**Issue by xpcbeyond** [seird/gotify-tray-cpp#9]
Please ask, I deployed gotify when using the redirecttohttps: true option, when both gotify-tray v0.5.3 and gotify-tray-cpp v0.0.7 do not have the ignore ssl option, do you have a plan to improve or say there are other ways to use this client normally? thanks

**Comment by xpcbeyond** [comment]
Thank you very much for your answer, but strangely, I exported the cert.crt of gotify server, and then imported it into gotify-tray-cpp, the Server url column showed a red reminder, I used the redirecttohttps: true option in gotify server config.yml file, but the two gotify clients could not be used normally. I do not know where else the client needs to be modified?
gotify-tray-cpp v.0.0.9 After installation, Gotify Tray++ version 0.0.8 is displayed in Windows programs and functions.

**Comment by seird** [comment]
> gotify-tray-cpp v.0.0.9 After installation, Gotify Tray++ version 0.0.8 is displayed in Windows programs and functions.

I forgot to commit the version files, but if you're seeing the certificate button, you're using the latest code.

This is the config I used for testing:
```
server:
  listenaddr: "0.0.0.0"
  port: 4500
  ssl:
    enabled: true
    redirecttohttps: true
    certfile: cert.pem
    certkey: key.pem
    port: 4501
database:
  dialect: sqlite3
  connection: data/gotify.db
passstrength: 10
registration: true
```
With this setup whenever I go to `https://192.168.1.29:4500` in a web browser, it isn't able to redirect to https, but it does work when I go to `https://192.168.1.29:4501`. Similarly for the server config in gotify tray++:

![Image](https://github.com/user-attachments/assets/355408dc-a1af-4406-bb03-53f568408447)

![Image](https://github.com/user-attachments/assets/0bfeb563-69ee-4622-bd3c-4b8e3fb8ae7f)

Also, the `CN` value in the certificate has to match the hostname you are trying to connect to:
![Image](https://github.com/user-attachments/assets/9ccafbb1-7c23-4b97-b2a0-9db2b0a5c9b3)

So, I think you could try the URL followed by the port you specified in the `config.yml`, e.g.: `https://yourserver.com:443`
